const mongoose = require('mongoose');
const compliantSchema = mongoose.Schema({
    farmerId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Farmer',
        required:true,
    },
    trackingId:{
        type:String,
        required:true
    },
    complainantName:{
        type:String,
        required:true
    },
    contact:{
        type:String,
        required:true
    },
    address:{
        type:String
    },
    pin:{
        type:Number
    },
    authority:{
        type:String,
        required:true
    },
    priority:{
        type:String,
        required:true
    },
    company:{
        type:String,
        required:true
    },
    complaintDetails:{
        type:String,
        required:true
    },
    stage:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Stage',
        default:'674d550dcd1e4fdc7a8285e7'
    },
    remark:{
        type:String
    },
    created_At:{
        type:Date,
        default:Date.now
    },
    updated_At:{
        type:Date
    },
    created_By:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Employee',
        required:true
    },
    updated_By:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Employee'
    }
})

const Complaint = mongoose.model("Complaint", compliantSchema);
module.exports = Complaint;